WeatherApplicationEntityFramework/WeatherApplication/Models/ArchieveWeatherData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeatherApplication.Models
{
    public class ArchieveWeatherData
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Data { get; set; }
        public int Day { get; set; }
        public int Night { get; set; }
        public string Description { get; set; }

        public ArchieveWeatherData() { }
        public ArchieveWeatherData(string city,string data, int day,int night,string description)
        {
            City=city;
            Data = data;
            Day = day;
            Night = night;
            Description = description;
        }
    }

}

WeatherApplicationEntityFramework/WeatherApplication/Models/WeatherData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeatherApplication.Models
{
    public class WeatherData
    {
        public class Coord
        {
            public double lon { get; set; }
            public double lat { get; set; }
        }

        public class City
        {
            public int id { get; set; }
            public string name { get; set; }
            public Coord coord { get; set; }
            public string country { get; set; }
            public int population { get; set; }
        }

        public class Temp
        {
            public double day { get; set; }
            public double min { get; set; }
            public double max { get; set; }
            public double night { get; set; }
            public double eve { get; set; }
            public double morn { get; set; }
            public int DayInCelsius()
            {
                return (int)Math.Round(day - 273.16);
            }
            public int NightInCelsius()
            {
                return (int)Math.Round(night - 273.16);
            }
        }

        public class Weather
        {
            public int id { get; set; }
            public string main { get; set; }
            public string description { get; set; }
            public string icon { get; set; }
        }

        public class List
        {
            public int dt { get; set; }
            public Temp temp { get; set; }
            public double pressure { get; set; }
            public int humidity { get; set; }
            public List<Weather> weather { get; set; }
            public double speed { get; set; }
            public int deg { get; set; }
            public int clouds { get; set; }
            public double? rain { get; set; }
        }

        public class RootObject
        {
            public City city { get; set; }
            public string cod { get; set; }
            public double message { get; set; }
            public int cnt { get; set; }
            public List<List> list { get; set; }
        }
    }
}

WeatherApplicationEntityFramework/WeatherApplication/Models/WeatherDataContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace WeatherApplication.Models
{
    public class WeatherDataContext:DbContext
    {
        public WeatherDataContext()
            :base("DbConnection") { }
          
        public DbSet<ArchieveWeatherData> weatherDataRecords { get; set; }
    }
}

WeatherApplicationEntityFramework/WeatherApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeatherApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WeatherApplicationEntityFramework/WeatherApplication/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeatherApplication.Services;
using Ninject;
using WeatherApplication.Models;
using System.Data.Entity;

namespace WeatherApplication.Controllers
{
    public class WeatherController : Controller
    {
        private IWeatherService service;
        WeatherDataContext bd = new WeatherDataContext();
        // GET: Weather
        public WeatherController(IWeatherService _service)
        {
            service = _service;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetWeather(string city,int term)
        {
            var result = service.GetWeatherForecast(city);
            for (int i = 0; i < term; i++)
            {
                var data = DateTime.Now;
                data=data.AddDays(i);
                int day = result.list[i].temp.DayInCelsius();
                int night = result.list[i].temp.NightInCelsius();
                string description = result.list[i].weather[0].description;
                ArchieveWeatherData wd = new ArchieveWeatherData(result.city.name, data.Date.ToString("dd/MM/yyyy"), day, night, description);
                bd.weatherDataRecords.Add(wd);
            }
            bd.SaveChanges();
            ViewBag.days = term;
            return View(result);
        }

        public ActionResult GetWeatherHistory()
        {
            ViewBag.records = bd.weatherDataRecords.ToList();
            return View();
        }

    }
}

WeatherApplicationEntityFramework/WeatherApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WeatherApplicationEntityFramework/WeatherApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WeatherApplicationEntityFramework/WeatherApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WeatherApplicationEntityFramework/WeatherApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Weather application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Get weather","Index","Weather")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WeatherApplicationEntityFramework/WeatherApplication/Views/Weather/GetWeather.cshtml
@model WeatherApplication.Models.WeatherData.RootObject

@{
    ViewBag.Title = "GetWeather";
    int days = (int)ViewBag.days;
}

<h2>Weather forecast for @Model.city.name</h2>

@for (int i = 0; i < days;i++ )
{
    var data = DateTime.Now;
    data=data.AddDays(i);
    <span>@data.Date.ToString("dd/MM/yyyy")</span><br>
    <span>Day temperature:</span>@Model.list[i].temp.DayInCelsius()<span>&deg</span><br>
    <span>Night temperature:</span>@Model.list[i].temp.NightInCelsius()<span>&deg</span><br>
    @Model.list[i].weather[0].description;<br>
    <p><hr></p>
}

WeatherApplicationEntityFramework/WeatherApplication/Views/Weather/GetWeatherHistory.cshtml
@{
    ViewBag.Title = "GetWeatherHistory";
    List<WeatherApplication.Models.ArchieveWeatherData> l = (List<WeatherApplication.Models.ArchieveWeatherData>)ViewBag.records;
}

<h2>Weather history</h2>

@for (int i = 0; i < l.Count; i++)
{
    if (i == 0)
    {
        <p><hr></p>
        <h3>Weather forecast for @l[i].City</h3><br>
    }
    <span>@l[i].Data</span><br>
    <span>Day temperature:</span>@l[i].Day<span>&deg</span><br>
    <span>Night temperature:</span>@l[i].Night<span>&deg</span><br>
    @l[i].Description;<br><br>
    if (i + 1 < l.Count && (l[i].City != l[i + 1].City))
    {
        <p><hr></p>
        <h3>Weather forecast for @l[i + 1].City</h3><br>
    }
}

WeatherApplicationEntityFramework/WeatherApplication/Views/Weather/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br />
<form action="Weather/GetWeather" method="post">
    <h2>Current weather in your city</h2>

    <input type="radio" name="term" value="1" checked> Today weather forecast<br>
    <input type="radio" name="term" value="3"> 3 days weather forecast<br>
     <input type="radio" name="term" value="7"> Week weather forecast<br>
    <input list="cities" name="city" required placeholder="City" />
    <datalist id="cities">
        <option value="Kyiv">
        <option value="Lviv">
        <option value="Kharkiv">
        <option value="Dnipropetrovsk">
        <option value="Odesa">
</datalist>
    <input type="submit" value="Submit" /> <br>
    @Html.ActionLink("Get weather history", "GetWeatherHistory", "Weather")
</form>